# Generated by Django 4.1.2 on 2022-12-17 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_mensajes_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(blank=True, default='/default.jpeg', null=True, upload_to='avatares/'),
        ),
    ]
